"""Markdown report generator for the quant pipeline.

Stitches strategy config, screener results, backtest stats, and LLM
recommendation into a single markdown file. Each section degrades
gracefully when its state key is absent.

Public API
----------
build_report(state)                        -> str   # markdown string
save_report(state, output_dir, strategy)   -> Path  # writes file
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _pct(v: Any, decimals: int = 1) -> str:
    if v is None:
        return "N/A"
    try:
        return f"{float(v):.{decimals}%}"
    except (TypeError, ValueError):
        return str(v)


def _f(v: Any, decimals: int = 2) -> str:
    if v is None:
        return "N/A"
    try:
        return f"{float(v):.{decimals}f}"
    except (TypeError, ValueError):
        return str(v)


def _signed_pct(v: Any) -> str:
    if v is None:
        return "N/A"
    try:
        sign = "+" if float(v) >= 0 else ""
        return f"{sign}{float(v):.1%}"
    except (TypeError, ValueError):
        return str(v)


def _or(v: Any, fallback: str = "N/A") -> str:
    return str(v) if v is not None else fallback


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _section_header(state: dict) -> str:
    strategy = state.get("strategy", {})
    name = strategy.get("name", "unknown")
    ts = state.get("timestamp", datetime.now().isoformat())
    date_str = ts[:10]
    decision = state.get("decision", {})
    verdict = decision.get("verdict", "")
    conviction = decision.get("conviction", "")

    verdict_line = ""
    if verdict:
        verdict_line = f"\n**Verdict: {verdict}** [{conviction} conviction]"

    return (
        f"# Quantitative Value Analysis — {name} — {date_str}"
        f"{verdict_line}\n\n"
        f"*Generated by the quant pipeline on {ts[:19].replace('T', ' ')}*\n"
    )


def _section_executive_summary(state: dict) -> str:
    lines = ["## Executive Summary\n"]

    decision = state.get("decision", {})
    bt = state.get("backtest", {})
    strategy = state.get("strategy", {})

    if decision.get("verdict"):
        verdict = decision["verdict"]
        conviction = decision.get("conviction", "")
        summary = decision.get("summary", "")
        lines.append(
            f"**Verdict: {verdict}** ({conviction} conviction)\n\n"
            f"{summary}\n"
        )
    else:
        # Summarise from backtest stats when no LLM decision
        name = strategy.get("name", "this strategy")
        if bt and "error" not in bt:
            cagr = bt.get("cagr", 0)
            vs_spy = bt.get("vs_spy")
            spy_str = f", {_signed_pct(vs_spy)} vs SPY" if vs_spy is not None else ""
            lines.append(
                f"The **{name}** strategy produced a {_pct(cagr)} CAGR over the "
                f"backtest window{spy_str}. LLM recommendation was not generated "
                f"(run without `--no-llm` and set `ANTHROPIC_API_KEY` to add it).\n"
            )
        else:
            lines.append(
                f"Pipeline ran without LLM synthesis. "
                f"See the Backtest Performance section for quantitative results.\n"
            )

    return "\n".join(lines)


def _section_strategy(state: dict) -> str:
    strategy = state.get("strategy")
    if not strategy:
        return "## Strategy Configuration\n\n*Not available.*\n"

    sc = strategy.get("screen", {})
    po = strategy.get("portfolio", {})
    bt = strategy.get("backtest", {})

    def _opt(v: Any, fmt: str = "{}") -> str:
        return fmt.format(v) if v is not None else "—"

    lines = [
        "## Strategy Configuration\n",
        f"**Name:** {strategy.get('name', 'N/A')}  ",
        f"**Description:** {strategy.get('description', '').strip()}\n",
        "### Screening Thresholds\n",
        f"| Parameter | Value |",
        f"|---|---|",
        f"| Min composite score | {_opt(sc.get('min_score'))} / 100 |",
        f"| Max trailing P/E | {_opt(sc.get('max_pe'))} |",
        f"| Max P/B | {_opt(sc.get('max_pb'))} |",
        f"| Min ROE | {_opt(sc.get('min_roe'), '{:.0%}')} |",
        f"| Max debt / equity | {_opt(sc.get('max_debt_to_equity'))}% |",
        f"| Min market cap | ${_opt(sc.get('min_market_cap'), '{:,.0f}')} |",
        "",
        "### Portfolio & Backtest Rules\n",
        f"| Parameter | Value |",
        f"|---|---|",
        f"| Max positions | {po.get('max_positions', 'N/A')} |",
        f"| Position sizing | {po.get('position_size', 'N/A')} weight |",
        f"| Backtest window | {bt.get('years', 'N/A')} years |",
        f"| Rebalance | {bt.get('rebalance', 'N/A')} |",
        f"| Commission | {_pct(bt.get('commission'), 2)} per trade |",
        f"| Cash buffer | {_pct(bt.get('cash_pct'), 0)} |",
    ]
    return "\n".join(lines) + "\n"


def _section_screener(state: dict) -> str:
    screen = state.get("screen", {})
    top_picks = screen.get("top_picks", [])
    tickers = state.get("tickers", [])

    if not top_picks and not tickers:
        return "## Universe & Screener Results\n\n*Not available.*\n"

    lines = ["## Universe & Screener Results\n"]

    total = screen.get("total_scored")
    filtered = screen.get("filtered")
    if total:
        lines.append(
            f"Screened {total} tickers; {filtered} passed strategy filters; "
            f"top {len(top_picks)} selected for backtest.\n"
        )
    elif tickers:
        lines.append(f"Explicit ticker list provided ({len(tickers)} tickers).\n")

    if top_picks and top_picks[0].get("total_score") is not None:
        # Full screener output — show a scored table
        lines += [
            "| # | Ticker | Name | Score | Grade | P/E | P/B | ROE | Div Yield |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
        for i, r in enumerate(top_picks[:25], 1):
            pe  = _f(r.get("pe_trailing"), 1) if r.get("pe_trailing") else "—"
            pb  = _f(r.get("pb_ratio"), 2)    if r.get("pb_ratio")    else "—"
            roe = _pct(r.get("roe"))           if r.get("roe")         else "—"
            div = _pct(r.get("dividend_yield"), 2) if r.get("dividend_yield") else "—"
            lines.append(
                f"| {i} | **{r.get('ticker', '?')}** "
                f"| {r.get('name', '')[:28]} "
                f"| {r.get('total_score', '?')} "
                f"| {r.get('grade', '?')} "
                f"| {pe} | {pb} | {roe} | {div} |"
            )
    else:
        # Minimal list — just tickers
        lines.append(", ".join(f"**{t}**" for t in tickers))

    return "\n".join(lines) + "\n"


def _section_backtest(state: dict) -> str:
    bt = state.get("backtest", {})

    if not bt:
        return "## Backtest Performance\n\n*Not available.*\n"

    if "error" in bt:
        return f"## Backtest Performance\n\nBacktest could not be completed: {bt['error']}\n"

    spy_cagr = bt.get("spy_cagr")
    vs_spy   = bt.get("vs_spy")
    spy_row  = (
        f"\n| SPY CAGR (benchmark) | {_pct(spy_cagr)} |"
        f"\n| vs SPY | {_signed_pct(vs_spy)} |"
    ) if spy_cagr is not None else ""

    win_rate_val = bt.get("win_rate")
    win_rate_str = _pct(win_rate_val) if win_rate_val is not None else "N/A"

    lines = [
        "## Backtest Performance\n",
        f"Equal-weight, {state.get('strategy', {}).get('backtest', {}).get('rebalance', 'periodic')} "
        f"rebalance over {bt.get('years')} years "
        f"({bt.get('start_date')} to {bt.get('end_date')}), "
        f"{bt.get('n_tickers')} tickers.\n",
        "| Metric | Value |",
        "|---|---|",
        f"| CAGR | {_pct(bt.get('cagr'))} |",
        f"| Total return | {_pct(bt.get('total_return'))} |",
        f"| Sharpe ratio | {_f(bt.get('sharpe'))} |",
        f"| Sortino ratio | {_f(bt.get('sortino'))} |",
        f"| Max drawdown | {_pct(bt.get('max_drawdown'))} |",
        f"| Win rate (rebalance periods) | {win_rate_str} |" + spy_row,
        "",
        "### Bias Disclaimer\n",
        bt.get(
            "note",
            "Survivorship and lookahead bias present. Results are directionally "
            "indicative only and should not be used for live trading decisions.",
        ),
    ]
    return "\n".join(lines) + "\n"


def _section_recommendation(state: dict) -> str:
    decision = state.get("decision", {})

    if not decision:
        return (
            "## Investment Recommendation\n\n"
            "*LLM recommendation not generated. "
            "Re-run without `--no-llm` and set `ANTHROPIC_API_KEY`.*\n"
        )

    if not decision.get("verdict"):
        raw = decision.get("raw", "")
        return (
            "## Investment Recommendation\n\n"
            f"*LLM response could not be parsed.*\n\n"
            + (f"Raw output:\n\n```\n{raw[:800]}\n```\n" if raw else "")
        )

    verdict    = decision["verdict"]
    conviction = decision.get("conviction", "")
    summary    = decision.get("summary", "")
    guidance   = decision.get("position_guidance", "")
    model      = decision.get("model", "")

    def _bullet_list(items: list[str], prefix: str) -> str:
        if not items:
            return ""
        return "\n".join(f"- {prefix}{item}" for item in items) + "\n"

    lines = [
        "## Investment Recommendation\n",
        f"**Verdict: {verdict}** — {conviction} conviction\n",
    ]
    if summary:
        lines.append(f"{summary}\n")

    pros  = decision.get("pros", [])
    cons  = decision.get("cons", [])
    risks = decision.get("risks", [])

    if pros:
        lines += ["\n**Strengths**\n", _bullet_list(pros, "")]
    if cons:
        lines += ["\n**Weaknesses**\n", _bullet_list(cons, "")]
    if risks:
        lines += ["\n**Risks**\n", _bullet_list(risks, "")]
    if guidance:
        lines += ["\n**Position Guidance**\n", f"{guidance}\n"]
    if model:
        lines.append(f"\n*Analysis generated by {model}*\n")

    return "\n".join(lines)


def _section_pipeline_log(state: dict) -> str:
    agent_log = state.get("agent_log", [])
    errors    = state.get("errors", [])

    lines = ["## Pipeline Log\n"]

    if agent_log:
        lines += [
            "| Step | Status | Detail |",
            "|---|---|---|",
        ]
        for entry in agent_log:
            detail = str(entry.get("detail", ""))[:80]
            lines.append(
                f"| {entry.get('agent', '?')} "
                f"| {entry.get('status', '?')} "
                f"| {detail} |"
            )
        lines.append("")

    if errors:
        lines.append(f"**Warnings / Errors ({len(errors)})**\n")
        for e in errors:
            lines.append(f"- {e}")
    else:
        lines.append("*No errors or warnings.*")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_report(state: dict) -> str:
    """Build and return the full markdown report from pipeline state.

    Gracefully omits sections whose state keys are absent.
    """
    sections = [
        _section_header(state),
        _section_executive_summary(state),
        _section_strategy(state),
        _section_screener(state),
        _section_backtest(state),
        _section_recommendation(state),
        _section_pipeline_log(state),
    ]
    return "\n---\n\n".join(s.rstrip() for s in sections) + "\n"


def save_report(state: dict, output_dir: Path, strategy_name: str) -> Path:
    """Write the markdown report to *output_dir* and return the file path."""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = output_dir / f"quant_{strategy_name}_{ts}.md"
    path.write_text(build_report(state), encoding="utf-8")
    return path
